export const adminSidebarMenu = [
  {
    type: "link",
    label: "Dashboard",
    permissionKey: "dashboard",
    path: "/admin/food",
    icon: "LayoutDashboard",
  },
  {
    type: "link",
    label: "Point of Sale",
    permissionKey: "pos",
    path: "/admin/food/point-of-sale",
    icon: "CreditCard",
  },
  {
    type: "section",
    label: "MENU MANAGEMENT",
    permissionKey: "food_management",
    items: [
      {
        type: "link",
        label: "Menu Approval",
        permissionKey: "food_approval",
        path: "/admin/food/food-approval",
        icon: "CheckCircle2",
      },
      {
        type: "expandable",
        label: "Menus",
        permissionKey: "foods",
        icon: "Utensils",
        subItems: [
          { label: "Restaurant Menus List", path: "/admin/food/foods", permissionKey: "list" },
          { label: "Restaurant Addons List", path: "/admin/food/addons", permissionKey: "addons" },
        ],
      },
      {
        type: "expandable",
        label: "Categories",
        permissionKey: "categories",
        icon: "FolderTree",
        subItems: [{ label: "Category", path: "/admin/food/categories", permissionKey: "list" }],
      },
    ],
  },
  {
    type: "section",
    label: "RESTAURANT MANAGEMENT",
    permissionKey: "restaurant_management",
    items: [
      {
        type: "link",
        label: "Zone Setup",
        permissionKey: "zone_setup",
        path: "/admin/food/zone-setup",
        icon: "MapPin",
      },
      {
        type: "expandable",
        label: "Restaurants",
        permissionKey: "restaurants",
        icon: "UtensilsCrossed",
        subItems: [
          { label: "All Restaurants", path: "/admin/food/restaurants", permissionKey: "list" },
          { label: "Restaurant Commission", path: "/admin/food/restaurants/commission", permissionKey: "commission" },
          { label: "New Joining Request", path: "/admin/food/restaurants/joining-request", permissionKey: "joining_request" },
          { label: "Zone Hub", path: "/admin/food/restaurants/zone-hubs", permissionKey: "joining_request" },
          { label: "COD Deposit Verification", path: "/admin/food/restaurants/cod-verification", permissionKey: "joining_request" },
          { label: "Restaurant Reviews", path: "/admin/food/restaurants/reviews", permissionKey: "reviews" },
          { label: "Restaurant Complaints", path: "/admin/food/restaurants/complaints", permissionKey: "complaints" },
        ],
      },
    ],
  },
  {
    type: "section",
    label: "ORDER MANAGEMENT",
    permissionKey: "order_management",
    items: [
      {
        type: "expandable",
        label: "Orders",
        permissionKey: "orders",
        icon: "FileText",
        subItems: [
          { label: "All", path: "/admin/food/orders/all", permissionKey: "all" },
          { label: "Scheduled", path: "/admin/food/orders/scheduled", permissionKey: "scheduled" },
          { label: "Pending", path: "/admin/food/orders/pending", permissionKey: "pending" },
          { label: "Accepted", path: "/admin/food/orders/accepted", permissionKey: "accepted" },
          { label: "Processing", path: "/admin/food/orders/processing", permissionKey: "processing" },
          { label: "Food On The Way", path: "/admin/food/orders/food-on-the-way", permissionKey: "out_for_delivery" },
          { label: "Delivered", path: "/admin/food/orders/delivered", permissionKey: "delivered" },
          { label: "Cancelled", path: "/admin/food/orders/canceled", permissionKey: "cancelled" },
          { label: "Restaurant cancelled", path: "/admin/food/orders/restaurant-cancelled", permissionKey: "restaurant_cancelled" },
          { label: "Payment Failed", path: "/admin/food/orders/payment-failed", permissionKey: "payment_failed" },
          { label: "Refunded", path: "/admin/food/orders/refunded", permissionKey: "refunded" },
          { label: "Offline Payments", path: "/admin/food/orders/offline-payments", permissionKey: "offline_payments" },
        ],
      },
      {
        type: "link",
        label: "Order Detect Delivery",
        permissionKey: "order_detect_delivery",
        path: "/admin/food/order-detect-delivery",
        icon: "Truck",
      },
    ],
  },
  {
    type: "section",
    label: "PROMOTIONS MANAGEMENT",
    permissionKey: "promotions_management",
    items: [
      {
        type: "link",
        label: "Restaurant Coupons & Offers",
        permissionKey: "coupons",
        path: "/admin/food/coupons",
        icon: "Gift",
      },
      {
        type: "link",
        label: "Coupons Request",
        permissionKey: "coupons",
        path: "/admin/food/coupons-request",
        icon: "FileCheck",
      },
    ],
  },
  {
    type: "section",
    label: "REFERRAL & REWARDS",
    permissionKey: "referral_rewards",
    items: [
      { type: "link", label: "Referral Settings", permissionKey: "referral_settings", path: "/admin/food/referral-settings", icon: "Gift" },
    ],
  },
  {
    type: "section",
    label: "CUSTOMER MANAGEMENT",
    permissionKey: "customer_management",
    items: [
      {
        type: "link",
        label: "All Users",
        permissionKey: "customers",
        path: "/admin/food/customers",
        icon: "Users",
      },
      {
        type: "link",
        label: "Customer Role Requests",
        permissionKey: "customers",
        path: "/admin/food/customer-role-requests",
        icon: "UserCheck",
      },
      {
        type: "link",
        label: "Support Tickets (User & Restaurant)",
        permissionKey: "support_tickets",
        path: "/admin/food/support-tickets",
        icon: "MessageSquare",
      },
    ],
  },
  /* Comment out the related restriction/check logic in the codebase instead of removing it completely.
  {
    type: "section",
    label: "SUBSCRIPTION MANAGEMENT",
    permissionKey: "subscription_management",
    items: [
      { type: "link", label: "Subscription Plans", permissionKey: "plans", path: "/admin/food/subscriptions", icon: "CreditCard" },
    ],
  },
  */
  {
    type: "section",
    label: "DELIVERYMAN MANAGEMENT",
    permissionKey: "deliveryman_management",
    items: [
      { type: "link", label: "Delivery Cash Limit", permissionKey: "cash_limit", path: "/admin/food/delivery-cash-limit", icon: "IndianRupee" },
      { type: "link", label: "Delivery & Platform Fee", permissionKey: "fee_settings", path: "/admin/food/fee-settings", icon: "IndianRupee" },
      { type: "link", label: "Delivery Speed Options", permissionKey: "fee_settings", path: "/admin/food/delivery-speed-options", icon: "Zap" },
      { type: "link", label: "Cash limit settlement", permissionKey: "settlement", path: "/admin/food/cash-limit-settlement", icon: "Receipt" },
      { type: "link", label: "Cash Pay Requests", permissionKey: "settlement", path: "/admin/food/cash-pay-requests", icon: "ClipboardCheck" },
      { type: "link", label: "Delivery Withdrawal", permissionKey: "withdrawal", path: "/admin/food/delivery-withdrawal", icon: "Wallet" },
      { type: "link", label: "Delivery boy Wallet", permissionKey: "wallet", path: "/admin/food/delivery-boy-wallet", icon: "PiggyBank" },
      { type: "link", label: "Delivery Boy Commission", permissionKey: "commission", path: "/admin/food/delivery-boy-commission", icon: "IndianRupee " },
      { type: "link", label: "Delivery Emergency Help", permissionKey: "emergency_help", path: "/admin/food/delivery-emergency-help", icon: "Phone" },
      { type: "link", label: "Delivery Support Tickets", permissionKey: "support_tickets", path: "/admin/food/delivery-support-tickets", icon: "MessageSquare" },
      {
        type: "expandable",
        label: "Deliveryman",
        permissionKey: "deliveryman",
        icon: "Package",
        subItems: [
          { label: "New Join Request", path: "/admin/food/delivery-partners/join-request", permissionKey: "join_request" },
          { label: "All Drivers", path: "/admin/food/delivery-partners", permissionKey: "list" },
          { label: "Deliveryman Reviews", path: "/admin/food/delivery-partners/reviews", permissionKey: "reviews" },
          { label: "Bonus", path: "/admin/food/delivery-partners/bonus", permissionKey: "bonus" },
          { label: "Earning Addon", path: "/admin/food/delivery-partners/earning-addon", permissionKey: "earning_addon" },
          { label: "Earning Addon History", path: "/admin/food/delivery-partners/earning-addon-history", permissionKey: "earning_addon_history" },
          { label: "Delivery Earning", path: "/admin/food/delivery-partners/earnings", permissionKey: "earnings" },
        ],
      },
    ],
  },
  {
    type: "section",
    label: "HELP & SUPPORT",
    permissionKey: "help_support",
    items: [
      { type: "link", label: "User Feedback", permissionKey: "user_feedback", path: "/admin/food/contact-messages", icon: "Mail" },
      { type: "link", label: "Safety Emergency Reports", permissionKey: "safety_reports", path: "/admin/food/safety-emergency-reports", icon: "AlertTriangle" },
    ],
  },
  {
    type: "section",
    label: "REPORT MANAGEMENT",
    permissionKey: "report_management",
    items: [
      { type: "link", label: "Transaction Report", permissionKey: "transactions", path: "/admin/food/transaction-report", icon: "FileText" },
      { type: "link", label: "Order Report", permissionKey: "orders", path: "/admin/food/order-report/regular", icon: "FileText" },
      { type: "link", label: "Tax Report", permissionKey: "tax", path: "/admin/food/tax-report", icon: "Receipt" },
      {
        type: "expandable",
        label: "Restaurant Report",
        permissionKey: "restaurant_report",
        icon: "FileText",
        subItems: [{ label: "Restaurant Report", path: "/admin/food/restaurant-report", permissionKey: "view" }],
      },
      {
        type: "expandable",
        label: "Customer Report",
        permissionKey: "customer_report",
        icon: "FileText",
        subItems: [{ label: "Feedback Experience", path: "/admin/food/customer-report/feedback-experience", permissionKey: "feedback_experience" }],
      },
    ],
  },
  {
    type: "section",
    label: "TRANSACTION MANAGEMENT",
    permissionKey: "transaction_management",
    items: [
      { type: "link", label: "Restaurant Withdraws", permissionKey: "restaurant_withdraws", path: "/admin/food/restaurant-withdraws", icon: "CreditCard" },
      { type: "link", label: "Onboarding Fee Management", permissionKey: "restaurant_withdraws", path: "/admin/food/onboarding-fee-management", icon: "Settings" },
      { type: "link", label: "Onboarding Payments", permissionKey: "restaurant_withdraws", path: "/admin/food/onboarding-payments", icon: "Receipt" },
    ],
  },
  {
    type: "section",
    label: "BANNER SETTINGS",
    permissionKey: "banner_settings",
    items: [
      { type: "link", label: "Landing Page Management", permissionKey: "landing_page", path: "/admin/food/hero-banner-management", icon: "Image" },
    ],
  },
  {
    type: "section",
    label: "DINING MANAGEMENT",
    permissionKey: "dining_management",
    items: [
      { type: "link", label: "Dining Banners", permissionKey: "banners", path: "/admin/food/dining-management", icon: "UtensilsCrossed" },
      { type: "link", label: "Dining List", permissionKey: "list", path: "/admin/food/dining-list", icon: "FileText" },
    ],
  },
  {
    type: "section",
    label: "STAFF MANAGEMENT",
    permissionKey: "staff_management",
    items: [
      { type: "link", label: "Roles & Permissions", permissionKey: "roles", path: "/admin/food/employee-role", icon: "Lock" },
      { type: "link", label: "Employee List", permissionKey: "list", path: "/admin/food/employees", icon: "Users" },
    ],
  },
  {
    type: "section",
    label: "SYSTEM SETTINGS",
    permissionKey: "system_settings",
    items: [
      { type: "link", label: "Broadcast Notification", permissionKey: "broadcast", path: "/admin/food/broadcast-notification", icon: "Bell" },
      { type: "link", label: "Deleted Accounts", permissionKey: "deleted_accounts", path: "/admin/food/deleted-accounts", icon: "Trash2" },
    ],
  },
  {
    type: "section",
    label: "PAGES & SOCIAL MEDIA",
    permissionKey: "pages_social_media",
    items: [
      { type: "link", label: "About Us", permissionKey: "about", path: "/admin/food/pages-social-media/about", icon: "Globe" },
      { type: "link", label: "Terms & Conditions", permissionKey: "terms", path: "/admin/food/pages-social-media/terms", icon: "FileText" },
      { type: "link", label: "Privacy Policy", permissionKey: "privacy", path: "/admin/food/pages-social-media/privacy", icon: "Lock" },
      { type: "link", label: "Refund Policy", permissionKey: "refund", path: "/admin/food/pages-social-media/refund", icon: "Receipt" },
      { type: "link", label: "Shipping Policy", permissionKey: "shipping", path: "/admin/food/pages-social-media/shipping", icon: "Truck" },
      { type: "link", label: "Cancellation Policy", permissionKey: "cancellation", path: "/admin/food/pages-social-media/cancellation", icon: "X" },
    ],
  },
];
